services:
  ubuntu-desktop:
    # Тег :ubuntu-mate-kasmvnc переключает контейнер на чистый KasmVNC без багнутых видео-плееров
    image: 'lscr.io/linuxserver/webtop:ubuntu-mate-kasmvnc'
    container_name: ubuntu_gui
    security_opt:
      - 'seccomp:unconfined'
      - 'apparmor:unconfined'
    privileged: true
    ipc: host
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Berlin
      SUBFOLDER: /
      WEBTOP_USER: abc
      PASSWORD: '${USER_PASSWORD}'
      KASMVNC_AUTO_SSL: '0'
    volumes:
      - './config:/config'
    shm_size: 2gb
    restart: unless-stopped