services:
  ubuntu-desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: ubuntu_gui
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    privileged: true
    ipc: host
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Berlin
      SUBFOLDER: /
      WEBTOP_USER: abc
      PASSWORD: '${USER_PASSWORD}'
      # ОТКЛЮЧАЕМ ВСЁ СЛОМАННОЕ В СТИЛЕ COOLIFY (БЕЗ ДЕФИСОВ! ЧЕРЕЗ ДВОЕТОЧИЕ):
      KASMVNC_AUTO_SSL: '0'
      WEBTOP_RENDERER: 'wmp'
      ENABLE_AUDIO: 'false'
    volumes:
      # ВНИМАНИЕ: Если Coolify ругается на локальный путь "./config", 
      # верни сюда полный путь, который он генерировал сам
      - ./config:/config
    shm_size: "1gb"
    restart: unless-stopped